name: Run Grub-Bot-Pipeline

on:
  schedule:
    - cron: '00 19 * * 4' # At 19:00 on Thursday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub Content to GitHub Runner
        uses: actions/checkout@v2 # checkout to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies/Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute (.py) Grub-Bot-App
        env:
          ENV_ESA: ${{ secrets.ENV_ESA }}
          ENV_ESF: ${{ secrets.ENV_ESF }}
          ENV_EK: ${{ secrets.ENV_EK }}
          ENV_EC: ${{ secrets.ENV_EC }}
          ENV_E_H: ${{ secrets.ENV_E_H }}
          ENV_E_P: ${{ secrets.ENV_E_P }}
        run: |
          echo "Executing :: grub-bot-app.py"
          python grub-bot-app.py
          echo "Finished :: grub-bot-app.py"